### ISSUE TITLE
supermanagerhome.js:96 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

### ISSUE THREAD

**Issue by zhoujiancn1** [elangobharathi/react-leaflet-freedraw#1]
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

I add it to Ant-design-pro, error

**Comment by elangobharathi** [comment]
Could you please provide me more information?

**Comment by elangobharathi** [comment]
Closing this due to lack of information.
