### ISSUE TITLE
Add leaflet-freedraw as a dependency

### ISSUE THREAD

**Issue by ineeve** [elangobharathi/react-leaflet-freedraw#2]
Add leaflet-freedraw as a dependency, so that developers don't have to install it manually, or at least add some info on the readme and npm page, so that users do not forget to do it.

**Comment by elangobharathi** [comment]
Thanks for letting me know. I have now added the information in the README. Similar to the react-leaflet pattern (leaflet is a peer dependency of react-leaflet), here leaflet-freedraw is a peer dependency.
