### ISSUE TITLE
[bug] Example broken : Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by mathieu-anderson** [elangobharathi/react-leaflet-freedraw#3]
### Situation and steps to reproduce (attempt to run the example locally) :
- cloned the project
- install all dependencies (add a `dependencies` key in `package.json` so that `example/index.js` can resolve dependencies)
- run `npm run example`
- build successful
- navigate to `http://localhost:8000`
- blank page, following messages in console : 

![Screen Shot 2019-04-15 at 10 41 47 AM](https://user-images.githubusercontent.com/20607294/56118865-25184e00-5f6b-11e9-837f-fbff3828d191.png)
- an `external_"leaflet"` seems to be created by Webpack :

![Screen Shot 2019-04-15 at 10 45 25 AM](https://user-images.githubusercontent.com/20607294/56119089-af60b200-5f6b-11e9-8ab4-18b47afe4a08.png)

Also tried to implement the example in my own project and got the exact same situation.

### The bug :
Unable to use the library, either in the example or in another context.

### Desired behaviour :
Being able to run the example either in the context of the library, or in other projects.

**Comment by elangobharathi** [comment]
@mathieu-anderson Sorry for the late action. Thank you for raising this.

The cause of this issue is that the peer dependencies needed to be installed manually. I have just added them to dev dependencies now.  It should be working now.
